import { useState, useEffect } from 'react';

/**
 * AiSummary — Dedicated AI Analyst Narrative Panel
 * Features:
 * 1. Typewriter effect for the attack narrative.
 * 2. Forensic Verdict section based on the report status.
 * 3. Clinical, authoritative B&W aesthetic.
 */
export default function AiSummary({ data }) {
  const { summary, attack_narrative, forensic_report, risk_level, findings = [] } = data;
  const [displayedNarrative, setDisplayedNarrative] = useState('');
  const [isTyping, setIsTyping] = useState(false);

  // Fallback narrative if AI fails but we have rule-based findings
  const fallbackNarrative = attack_narrative || (findings.length > 0 
    ? `I have reconstructed the attack vector from raw telemetry. The system detected ${findings.length} anomalous event(s) with ${risk_level} severity. Source identity patterns suggest targeted reconnaissance or automated exploitation attempts against the infrastructure.`
    : `Internal systems are operational. No high-confidence anomalies detected in the current datastream. Continuous monitoring is active.`);

  useEffect(() => {
    if (fallbackNarrative) {
      setIsTyping(true);
      setDisplayedNarrative('');
      let i = 0;
      const interval = setInterval(() => {
        setDisplayedNarrative(fallbackNarrative.slice(0, i));
        i++;
        if (i > fallbackNarrative.length) {
          clearInterval(interval);
          setIsTyping(false);
        }
      }, 15); // Slightly faster typing for better UX
      return () => clearInterval(interval);
    }
  }, [fallbackNarrative]);

  if (!summary && !attack_narrative && findings.length === 0) return null;

  return (
    <div className="glass-card slide-up ai-summary-panel">
      <div className="card-title">SISA AI ANALYST VERDICT</div>

      <div className="ai-status-header">
        <div className="ai-avatar">
          <div className="ai-avatar-inner" />
          <div className="ai-avatar-pulse" />
        </div>
        <div className="ai-meta">
          <div className="ai-name">CORE AI ANALYST (SISA-01)</div>
          <div className="ai-task">ANOMALY SCANNING & RECONSTRUCTION</div>
        </div>
        <div className={`ai-risk-tag ${risk_level}`}>
          {risk_level?.toUpperCase() || 'LOW'} RISK
        </div>
      </div>

      <div className="forensic-narrative-container">
        <div className="narrative-label">FORENSIC NARRATIVE GENERATED BY SISA-01</div>
        <div className="narrative-content">
          {displayedNarrative}
          {isTyping && <span className="terminal-cursor">_</span>}
        </div>
      </div>

      {forensic_report && (
        <div className="forensic-summary-box">
          <div className="summary-row">
            <span className="label">SYSTEM STATUS:</span>
            <span className={`value status-${forensic_report.status?.toLowerCase()}`}>
              {forensic_report.status || 'NOMINAL'}
            </span>
          </div>
          <div className="summary-row">
            <span className="label">PRIMARY EXPLOIT:</span>
            <span className="value">{forensic_report.root_cause || 'Pattern Analysis...'}</span>
          </div>
        </div>
      )}

      <div className="ai-summary-footer">
        <span className="summary-tag">VALIDATED BY SISA-LOGAI INTELLIGENCE MESH ◆ ENCRYPTED DATASTREAM</span>
      </div>
    </div>
  );
}
